services:
  vibevoice-realtime-openai-api:
    build: .
    image: vibevoice-realtime-openai-api
    container_name: vibevoice-realtime-openai-api
    ports:
      - "8880:8880"
    volumes:
      - ./models:/home/ubuntu/app/models
      - ./static:/home/ubuntu/app/static:ro
    environment:
      - CFG_SCALE=1.25  # (0.0 - 3.0, higher = more expressive)
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
